from .variable_node import NODE_CLASS_MAPPINGS as VARIABLE_NODE_CLASS_MAPPINGS
from .variable_node import NODE_DISPLAY_NAME_MAPPINGS as VARIABLE_NODE_DISPLAY_NAME_MAPPINGS

from .template_interpolation_node import NODE_CLASS_MAPPINGS as TEMPLATE_NODE_CLASS_MAPPINGS
from .template_interpolation_node import NODE_DISPLAY_NAME_MAPPINGS as TEMPLATE_NODE_DISPLAY_NAME_MAPPINGS

from .weighted_attributes_formatter_node import NODE_CLASS_MAPPINGS as WEIGHTED_ATTRIBUTES_FORMATTER_NODE_CLASS_MAPPINGS
from .weighted_attributes_formatter_node import NODE_DISPLAY_NAME_MAPPINGS as WEIGHTED_ATTRIBUTES_FORMATTER_NODE_DISPLAY_NAME_MAPPINGS

# Merge the dictionaries
NODE_CLASS_MAPPINGS = {
    **VARIABLE_NODE_CLASS_MAPPINGS,
    **TEMPLATE_NODE_CLASS_MAPPINGS,
    **WEIGHTED_ATTRIBUTES_FORMATTER_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **VARIABLE_NODE_DISPLAY_NAME_MAPPINGS,
    **TEMPLATE_NODE_DISPLAY_NAME_MAPPINGS,
    **WEIGHTED_ATTRIBUTES_FORMATTER_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]