from .nodes.multiclip_prompt_combinator import NODE_CLASS_MAPPINGS as MULTICLIP_PROMPT_COMBINATOR_NODE_CLASS_MAPPINGS
from .nodes.multiclip_prompt_combinator import NODE_DISPLAY_NAME_MAPPINGS as MULTICLIP_PROMPT_COMBINATOR_NODE_DISPLAY_NAME_MAPPINGS

from .nodes.template_interpolation_node import NODE_CLASS_MAPPINGS as TEMPLATE_NODE_CLASS_MAPPINGS
from .nodes.template_interpolation_node import NODE_DISPLAY_NAME_MAPPINGS as TEMPLATE_NODE_DISPLAY_NAME_MAPPINGS

from .nodes.variable_node import NODE_CLASS_MAPPINGS as VARIABLE_NODE_CLASS_MAPPINGS
from .nodes.variable_node import NODE_DISPLAY_NAME_MAPPINGS as VARIABLE_NODE_DISPLAY_NAME_MAPPINGS

from .nodes.weighted_attributes_formatter_node import NODE_CLASS_MAPPINGS as WEIGHTED_ATTRIBUTES_FORMATTER_NODE_CLASS_MAPPINGS
from .nodes.weighted_attributes_formatter_node import NODE_DISPLAY_NAME_MAPPINGS as WEIGHTED_ATTRIBUTES_FORMATTER_NODE_DISPLAY_NAME_MAPPINGS

from .nodes.lora_trigger_loader import NODE_CLASS_MAPPINGS as LORA_TRIGGER_LOADER_NODE_CLASS_MAPPINGS
from .nodes.lora_trigger_loader import NODE_DISPLAY_NAME_MAPPINGS as LORA_TRIGGER_LOADER_NODE_DISPLAY_NAME_MAPPINGS

# Merge the dictionaries
NODE_CLASS_MAPPINGS = {
    **LORA_TRIGGER_LOADER_NODE_CLASS_MAPPINGS,
    **MULTICLIP_PROMPT_COMBINATOR_NODE_CLASS_MAPPINGS,
    **TEMPLATE_NODE_CLASS_MAPPINGS,
    **VARIABLE_NODE_CLASS_MAPPINGS,
    **WEIGHTED_ATTRIBUTES_FORMATTER_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LORA_TRIGGER_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **MULTICLIP_PROMPT_COMBINATOR_NODE_DISPLAY_NAME_MAPPINGS,
    **TEMPLATE_NODE_DISPLAY_NAME_MAPPINGS,
    **VARIABLE_NODE_DISPLAY_NAME_MAPPINGS,
    **WEIGHTED_ATTRIBUTES_FORMATTER_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
